# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myuser', '0004_auto_20161021_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('VCode', models.CharField(max_length=6)),
            ],
        ),
    ]
