# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('url_manage', '0007_urls_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('pubDate', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_manage.Urls')),
            ],
        ),
    ]
