# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myuser.MyUser'),
        ),
    ]
