# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_manage', '0002_auto_20161026_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='last_check_time',
            field=models.CharField(max_length=50),
        ),
    ]
